version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - printenv
      - rm -rf node_modules
      - npm install
  build:
    commands:
      - npm run build -prod
  post_build:
    commands:
      - aws --region ap-southeast-2 s3 sync ./dist/ s3://acloud-makerlab-code-bucket-01/ --acl=public-read --delete
